APPLICATION_SERVER_TOKEN="this is the token" \
APPLICATION_SERVER="http://localhost:8200" \
DASHBOARD_SERVER="https://test-application.server7373.synology.me" \
DOMAIN="test-application.server7373.synology.me" \
STRIPE_JS="false" \
STRIPE_KEY="$SUBSCRIPTIONS_STRIPE_KEY" \
STRIPE_PUBLISHABLE_KEY="$SUBSCRIPTIONS_STRIPE_PUBLISHABLE_KEY" \
SUBSCRIPTION_WEBHOOK_ENDPOINT_SECRET="$SUBSCRIPTION_WEBHOOK_ENDPOINT_SECRET" \
PORT=8300 \
IP=0.0.0.0 \
node main.js 
